

#define LED_ORANGE_PORT 	GPIOD
#define LED_ORANGE_PIN 		GPIO_PIN_13

#define LED_GREEN_PORT 		GPIOD
#define LED_GREEN_PIN 		GPIO_PIN_12

#define LED_RED_PORT 		GPIOD
#define LED_RED_PIN 		GPIO_PIN_14

#define LED_BLUE_PORT 		GPIOD
#define LED_BLUE_PIN 		GPIO_PIN_15
